export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const ADD_COURSE = "ADD_COURSE";
export const BEST_STUDENTS = "BEST_STUDENTS";
export const LATEST_ENROLLMENTS = "LATEST_ENROLLMENTS";
export const SHOW_COURSES = "SHOW_COURSES";
